### ISSUE TITLE
Repo outdated

### ISSUE THREAD

**Issue by Rijgersberg** [NetherlandsForensicInstitute/hansken-extraction-plugin-template-python#4]
It has come to my attention that this version of the repo is outdated.

Can we explicitly mark it as such and point to the right repo? Or delete this one?

**Comment by remco-nfi** [comment]
I am very sorry we mised your comment.
This repo is intended to be the right repo. Did you find another repo, we might need to delete the other?

In #5 we have updated the template to the latest-gratest.
